language: c
env:
  global:
    secure: tKsXchpRFpGKGcIyiXtV0xPlqaFHIMtAbcmAktYTwk1iGlSBHrFyOx/tSzPGdXMhlIW/pQulMZIeiNOWutt4BZE2i4w5iLNEoC3Gx0SwhJaNrpCLql/O+vaMo+nCejub52MEU40uquyAh33CGlqeLttrgCJ9awRwVsHL7DSlsqA=
install:
- sudo sh -c 'echo deb http://ppa.launchpad.net/borgdylan/ppa/ubuntu precise main >> /etc/apt/sources.list'
- sudo apt-get update
- sudo apt-get -q -y --force-yes install cmake mono-devel mono-gmcs mono-xbuild nunit-console
script:
- xbuild /p:TestsEnabled=false
